

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt

services:

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    restart: unless-stopped

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    secrets:
      - credentials
      - db_password
    environment:
      CREDENTIALS_FILE: /run/secrets/credentials
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    ports:
      - "8443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: unless-stopped
